from __future__ import annotations

from typing import List, Optional, Protocol

from .entities import Marca, Persona, Vehiculo


class MarcaRepository(Protocol):
    def create(self, marca: Marca) -> Marca: ...

    def list(self, skip: int, limit: int) -> List[Marca]: ...

    def get(self, marca_id: int) -> Optional[Marca]: ...

    def update(self, marca_id: int, data: dict) -> Marca: ...

    def delete(self, marca_id: int) -> None: ...


class PersonaRepository(Protocol):
    def create(self, persona: Persona) -> Persona: ...

    def list(self, skip: int, limit: int) -> List[Persona]: ...

    def get(self, persona_id: int) -> Optional[Persona]: ...

    def update(self, persona_id: int, data: dict) -> Persona: ...

    def delete(self, persona_id: int) -> None: ...


class VehiculoRepository(Protocol):
    def create(self, vehiculo: Vehiculo) -> Vehiculo: ...

    def list(self, skip: int, limit: int) -> List[Vehiculo]: ...

    def get(self, vehiculo_id: int) -> Optional[Vehiculo]: ...

    def update(self, vehiculo_id: int, data: dict) -> Vehiculo: ...

    def delete(self, vehiculo_id: int) -> None: ...

    def add_propietario(self, vehiculo_id: int, persona_id: int) -> Vehiculo: ...

    def set_propietarios(self, vehiculo_id: int, propietarios_ids: List[int]) -> Vehiculo: ...

